export const seats = [
  { seat: "01", occupied: false },
  { seat: "02", occupied: true },
  { seat: "03", occupied: false },
  { seat: "04", occupied: true },
  { seat: "05", occupied: true },
  { seat: "06", occupied: false },
  { seat: "07", occupied: true },
  { seat: "08", occupied: false },
  { seat: "09", occupied: false },
  { seat: "10", occupied: true },
  { seat: "11", occupied: false },
  { seat: "12", occupied: true },
  { seat: "13", occupied: false },
  { seat: "14", occupied: false },
  { seat: "15", occupied: true },
  { seat: "16", occupied: true },
  { seat: "17", occupied: false },
  { seat: "18", occupied: true },
  { seat: "19", occupied: false },
  { seat: "20", occupied: true },
  { seat: "21", occupied: false },
  { seat: "22", occupied: false },
  { seat: "23", occupied: true },
  { seat: "24", occupied: true },
  { seat: "25", occupied: false },
  { seat: "26", occupied: false },
  { seat: "27", occupied: true },
  { seat: "28", occupied: true },
  { seat: "29", occupied: false },
  { seat: "30", occupied: false },
  { seat: "31", occupied: true },
  { seat: "32", occupied: false },
  { seat: "33", occupied: true },
  { seat: "34", occupied: false },
  { seat: "35", occupied: true },
  { seat: "36", occupied: false },
  { seat: "37", occupied: true },
  { seat: "38", occupied: true },
  { seat: "39", occupied: false },
  { seat: "40", occupied: true },
  { seat: "41", occupied: false },
  { seat: "42", occupied: false },
  { seat: "43", occupied: true },
  { seat: "44", occupied: true },
  { seat: "45", occupied: false },
  { seat: "46", occupied: false },
  { seat: "47", occupied: true },
];

export const leftSeats = [
  "08",
  "07",
  "04",
  "03",
  "12",
  "11",
  "14",
  "13",
  "16",
  "15",
  "20",
  "19",
  "24",
  "23",
  "28",
  "27",
  "32",
  "31",
  "36",
  "35",
  "40",
  "39",
  "44",
  "43",
  "48",
  "47",
];

export const rightSeats = [
  "02",
  "01",
  "06",
  "05",
  "10",
  "09",
  null,
  null,
  null,
  null, // separadores visuais
  "18",
  "17",
  "22",
  "21",
  "26",
  "25",
  "30",
  "29",
  "34",
  "33",
  "38",
  "37",
  "42",
  "41",
  "46",
  "45",
];
